config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#top'
  get 'pages/top'
  get "pages/profile", to: "pages#profile"

  resources :rooms, only: [:index, :new, :create, :destroy]
  get 'rooms/search'

  resources :reservations, only: [:index, :create, :destroy]
  get 'reservations/new', to: "reservations#new"
  get 'reservations/confirm', to: "reservations#confirm"

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :number_people, presence: true

    validate :minus_number
    validate :start_end_check
    validate :start_check

    belongs_to :room
    belongs_to :user

    private

    def minus_number
      errors.add(:number_people, "は一人以上にしてください。") if number_people&. <= 0
    end

    def start_end_check
      return if start_date.blank? || end_date.blank?
      errors.add(:end_date, "は開始日より前の日付は登録できません。") if self.end_date < self.start_date
    end

    def start_check
      return if start_date.blank?
      errors.add(:start_date, "は今日以降のものを選択してください") if start_date < Date.today
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.where(user_id: current_user.id)
  end

  def new
    @reservation = Reservation.new
    @room = Room.find(params[:id])
    @user_id = current_user.id

  end

  def confirm
    @reservation = Reservation.new(reservation_params)
    @room = Room.find_by(id: @reservation.room_id)
    render :new if @reservation.invalid?
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    if params[:back].present?
      render :new
      return
    elsif @reservation.save
      flash[:notice] = "予約が完了しました"
      redirect_to reservations_url
    end
  end
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to :reservations
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :number_people, :room_id, :user_id)
  end

end

app/views/reservations/confirm.html.erb
<h2>予約確認画面</h2>

<%= form_with model: @reservation do |f| %>
  <%= f.hidden_field :start_date, value: @reservation.start_date %>
  <%= f.hidden_field :end_date, value: @reservation.end_date %>
  <%= f.hidden_field :number_people, value: @reservation.number_people %>
  <%= f.hidden_field :room_id, value: @room.id %>
  <%= f.hidden_field :created_at, value: @reservation.created_at %>
  <%= f.hidden_field :updated_at, value: @reservation.updated_at %>
<table class = "table_new">
  <th>開始</th>
    <td><%= @reservation.start_date %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @reservation.end_date %></td>
  </tr>
  <tr>
    <th>宿泊日数</th>
    <td><%= @total_day = (@reservation.end_date - @reservation.start_date).to_i %></td>

  </tr>
  <tr>
    <th>人数</th>
    <td><%= @reservation.number_people %></td>
  </tr>
  <tr>
    <th>合計料金</th>
    <td><%= @total_price = @reservation.room.room_price * @reservation.number_people * (@reservation.end_date - @reservation.start_date).to_i %></td>
  </tr>
</table>
 <div>
    <ul>
      <li><%= f.submit "予約する"%></li>
      <li><%= link_to "戻る", :back %></li>
    </ul>
 </div>
<% end %>

app/views/reservations/index.html.erb
<h2>予約済みルーム一覧</h2>

<% if flash[:notice] %>
   <p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
 <thead>
  <tr>
   <th>画像</th>
   <th>ルーム名</th>
   <th>紹介</th>
   <th>合計料金</th>
   <th>開始日</th>
   <th>終了日</th>
   <th>予約確定日時</th>
   <th>削除</th>
  </tr>
 </thead>

 <tbody>
  <tr>
  <% @reservations.each do |reservation| %>
   <% @rooms = Room.where(id: reservation.room_id) %>
  <% @rooms.each do |room| %>

   <td><%= image_tag room.room_image.url, size: '100x100' %></td>
   <td><%= reservation.room.room_name %></td>
   <td><%= reservation.room.room_introduction %></td>
   <td><%= reservation.room.room_price * reservation.number_people * (reservation.end_date - reservation.start_date).to_i %></td>
   <td><%= reservation.start_date %></td>
   <td><%= reservation.end_date %></td>
   <td><%= reservation.created_at.to_s(:datetime_jp) %></td>
   <td><%= link_to "削除", reservation, method: :delete, data: { confirm: "本当に削除しますか？" }  %></td>
  </tr>
  <% end %>
  <% end %>
 </tbody>
</table>

app/views/reservations/new.html.erb
<h2>ルーム予約</h2>

<table class = "table_new">
 <tr>
   <td><%= image_tag @room.room_image.url, size: '100x100' %></td>
 </tr>
 <tr>
   <td><%= @room.room_name %></td>
 </tr>
 <tr>
   <td><%= @room.room_introduction %></td>
 </tr>
 <tr>
   <td>¥<%= @room.room_price %>/日</td>
 </tr>
 <tr>
   <td><%= @room.room_area %></td>
 </tr>
</table>

 <h2>部屋を予約する</h2>

 <%= render "shared/error", obj: @reservation %>

 <%= form_with model: @reservation, url: reservations_confirm_url, method: :get do |f| %>
  <%= f.hidden_field :room_id, value: @room.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :room_price, value: @room.room_price %>
    <table class = "table_new">
     <tr>
       <th><%= f.label :start_date ,"開始日" %></th>
       <td><%= f.date_field :start_date %></td>
     </tr>

     <tr>
       <th><%= f.label :end_date ,"終了日" %></th>
       <td><%= f.date_field :end_date %></td>
     </tr>

     <tr>
       <th><%= f.label :number_people ,"人数" %></th>
       <td><%= f.number_field :number_people %></td>
     </tr>
   </table>
   <div>
     <ul>
       <li><%= f.submit "予約確認"%></li>
     </ul>
   </div>
 <% end %>